---
- name: "checkout dot files"
  git:
    repo: http://github.com/tyjak/archlinux
    dest: ~/src/archlinux
    update: no
  tags: "dotfiles"

- name: "checkout vim files"
  git:
    repo: http://github.com/tyjak/vim-config
    dest: ~/src/vim-config
    update: no
  register: vim_config_installed
  tags: dotfiles

- name: "link common dot files"
  file:
    state: link
    src: ~/src/{{ item.src }}
    dest: ~/{{ item.dest }}
  with_items: link_common_items
  tags: "dotfiles"

- name: "link gui dot files"
  file:
    state: link
    src: ~/src/{{ item.src }}
    dest: ~/{{ item.dest }}
  with_items: link_gui_items
  when: gui
  tags: "dotfiles"

- name: "vim install vundle"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    update: no
  tags: dotfiles

- name: "init vim configuration"
  command: vim +PluginInstall +qall
  when: vim_config_installed|changed
  tags: dotfiles

- name: vimfile backup dir
  file: path=~/.vimfiles/bak state=directory recurse=yes
  tags: dotfiles

- name: vimfile undo dir
  file: path=~/.vimfiles/undo state=directory
  tags: dotfiles

- include: config.yml
  when: config|default(false)

- include: i3.yml
  when: i3|default(false)

- include: vpn_adsnovo.yml
  when: vpn|default(false)
  tags: vpn
