---
- name: "checkout dot files"
  git:
    repo: http://github.com/tyjak/archlinux
    dest: ~/src/archlinux
    update: no
  tags: "dotfiles"

- name: "checkout vim files"
  git:
    repo: http://github.com/tyjak/vim-config
    dest: ~/src/vim-config
    update: no
  register: vim_config_installed
  tags: dotfiles

- name: "link common dot files"
  file:
    state: link
    src: ~/src/{{ item.src }}
    dest: ~/{{ item.dest }}
  with_items: "{{ link_common_items }}"
  tags: "dotfiles"

- name: "link gui dot files"
  file:
    state: link
    src: ~/src/{{ item.src }}
    dest: ~/{{ item.dest }}
    force: yes
  with_items: "{{ link_gui_items }}"
  when: gui
  tags: "dotfiles"

#FIXME: pb with initialisation without terminal
#- name: "init vim configuration"
#command: vim +PlugInstall +qall
#when: vim_config_installed|changed
#tags: dotfiles

- name: vimfile backup dir
  file: path=~/.vimfiles/bak state=directory recurse=yes
  tags: dotfiles

- name: vimfile undo dir
  file: path=~/.vimfiles/undo state=directory
  tags: dotfiles

#FIXME some config (vimb) depends on share folder, that shouldn't be
- name: enable syncthing
  command: systemctl --user enable syncthing.service
  register: enable_syncthing
  changed_when: enable_syncthing|success
  tags: syncthing

- name: start syncthing
  command: systemctl --user start syncthing.service
  when: enable_syncthing|success
  tags: syncthing

- include: config.yml
  when: config|default(false)

- include: i3.yml
  when: i3|default(false)

- include: vpn_ppp_adsnovo.yml
  when: vpn is defined and vpn.ppp|default(false)
  tags: vpn

- include: vpn_opvn_adsnovo.yml
  when: vpn is defined and vpn.openvpn|default(false)
  tags: vpn
