---

- name: install openvpn
  sudo: yes
  pacman: name=openvpn

- name: test if adsnovo config is present
  stat: path=/etc/openvpn/adsnovo.conf
  register: adsnovo_conf

- name: copy and install adsnovo config
  sudo: yes
  shell: 'ansible-vault decrypt --output=/etc/openvpn/adsnovo_openvpn.tar.gz roles/user/files/vpn/adsnovo_openvpn.vault && cd /etc/openvpn && tar -xzf adsnovo_openvpn.tar.gz && rm adsnovo_openvpn.tar.gz'
  when: adsnovo_conf.stat.exists == False
  tags: vpn

- name: enable adsnovo vpn service
  sudo: yes
  service: name=openvpn@adsnovo enabled=yes
  tags: vpn

