---

- name: restart i3
  command: i3-msg restart
  register: command_result
  failed_when: command_result.stderr

- name: restart syncthing
  systemd:
    name: syncthing
    state: restarted
    scope: user
  listen: "restart syncthing"

