---
- name: set hostname
  sudo: yes
  lineinfile: dest=/etc/hostname regexp="^{{ hostname|default(ansible_nodename) }}" line="{{ hostname|default(ansible_nodename) }}" create=yes state=present backrefs=yes
  tags: hostname

- name: set hosts
  sudo: yes
  lineinfile: dest=/etc/hosts regexp="{{ item.regexp }}" line="{{ item.line }}" create=yes state=present backrefs=yes
  with_items:
    - regexp: '^127.*localhost$'
      line: "127.0.0.1  {{ hostname|default(ansible_nodename) }}.localdomain  {{ hostname|default(ansible_nodename) }}"
    - regexp: '^::1.*localhost$'
      line: "::1  {{ hostname|default(ansible_nodename) }}.localdomain  {{ hostname|default(ansible_nodename) }}"
  tags: hostname

- name: set timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/Europe/Paris dest=/etc/localtime state=link force=yes

- name: configure fr locale
  sudo: yes
  lineinfile:
    dest: /etc/locale.gen
    state: present
    regexp: '^#(fr_FR.UTF-8.*)$'
    line: 'fr_FR.UTF-8 UTF-8'
    backrefs: yes
  register: has_configured

- name: locale gen
  sudo: yes
  command: locale-gen
  when: has_configured|failed

- name: set system locale
  sudo: yes
  command: "localectl set-locale LANG=fr_FR.UTF-8"
  when: has_configured|failed

- name: set keyboard
  sudo: yes
  command: "localectl set-keymap --no-convert fr"
  when: has_configured|failed

