---
- name: set timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/Europe/Paris dest=/etc/localtime state=link force=yes

- name: "configure fr locale"
  sudo: yes
  lineinfile:
    dest: /etc/locale.gen
    state: present
    regexp: '^#(fr_FR.UTF-8.*)$'
    line: 'fr_FR.UTF-8 UTF-8'

- name: "locale gen"
  sudo: yes
  command: locale-gen

- name: set system locale
  sudo: yes
  command: "localectl set-locale LANG=fr_FR.UTF-8"

- name: set keyboard
  sudo: yes
  command: "localectl set-keymap --no-convert fr"

