---
# install gui packages

- name: install pacman gui package
  sudo: yes
  pacman: name={{ item }}
  with_items: gui_pacman_package

- name: get new packages to install
  command: yaourt -Q {{ item }}
  register: packages_presence
  with_items: gui_yaourt_packages
  ignore_errors: yes
  changed_when: packages_presence|failed

- name: install yaourt packages
  sudo: no
  command: /usr/bin/yaourt --force --noconfirm -S {{ item.item }}
  when: item|failed
  with_items: packages_presence.results
  ignore_errors: yes
  
- name: get new fonts to install
  command: yaourt -Q {{ item }}
  register: fonts_presence
  with_items: fonts_package
  changed_when: fonts_presence|failed
  ignore_errors: yes
  tags: fonts

- name: install fonts package
  sudo: no
  command: /usr/bin/yaourt --noconfirm -S {{ item.item }}
  with_items: fonts_presence.results
  when: item|failed
  ignore_errors: yes
  tags: fonts

- name: get host theme packages
  command: yaourt -Q {{ item }}
  register: theme_presence
  with_items: theme_package
  when: theme_package|default(false)
  changed_when: theme_presence|failed
  ignore_errors: yes
  tags: theme

- name: install theme package
  sudo: no
  command: /usr/bin/yaourt --noconfirm -S {{ item.item }}
  with_items: theme_presence.results
  when: item|failed
  ignore_errors: yes
  tags: theme

