---
# install gui packages

- name: install pacman gui package
  become: true
  pacman: name={{ gui_pacman_package }}

- name: get new packages to install
  command: yaourt -Q {{ item }}
  register: packages_presence
  with_items: "{{ gui_yaourt_packages }}"
  ignore_errors: yes
  changed_when: packages_presence is failed
  tags: test

- name: install yaourt packages
  become: false
  command: /usr/bin/yaourt --force --noconfirm -S {{ item.item }}
  when: item is failed
  with_items: "{{ packages_presence.results }}"
  ignore_errors: yes

- name: get host theme packages
  command: yaourt -Q {{ item }}
  register: theme_presence
  with_items: "{{ theme_package }}"
  when: theme_package is defined
  changed_when: theme_presence is failed
  ignore_errors: yes
  tags: theme

- name: install theme package
  become: false
  command: /usr/bin/yaourt --force --noconfirm -S {{ item.item }}
  with_items: "{{ theme_presence.results }}"
  when: item is failed
  ignore_errors: yes
  tags: theme

