---
# pacman base package
- name: update pacman cache
  sudo: yes
  pacman: update_cache=yes

- name: install base package
  sudo: yes
  pacman: name={{ item }}
  with_items: package

# infinalty add repo
#- include: configure_pacman.yml

# install yaourt
- include: install_yaourt.yml

- include: configure_locale.yml

- include: gui.yml
  when: gui
  tags: gui

- name: has wifi ?
  shell: dmesg | grep "WLAN"
  register: has_wifi
  tags: wifi

- debug: msg={{ has_wifi.changed }}
  tags: wifi

- name: install wifi
  sudo: yes
  pacman: name=wpa_supplicant state=present
  when: has_wifi.changed
  tags: wifi

- name: get host misc packages
  command: yaourt -Q {{ item }}
  register: misc_presence
  with_items: misc_package
  changed_when: misc_presence|failed
  when: misc_package|default(false)
  ignore_errors: yes
  tags: misc

- name: install misc package
  sudo: no
  command: /usr/bin/yaourt --noconfirm -S {{ item.item }}
  with_items: misc_presence.results
  when: item|failed and gui
  ignore_errors: yes
  tags: misc

- name: enable additional service
  sudo: yes
  service: name={{ item }} state=started enabled=yes
  with_items: additional_service
  when: misc_presence.changed
  tags: misc

- name: enable syncthing
  command: systemctl --user enable syncthing.service
  register: enable_syncthing
  changed_when: enable_syncthing.stderr
  tags: syncthing

- name: start syncthing
  command: systemctl --user start syncthing.service
  when: enable_syncthing.stderr
  tags: syncthing

  #- include: install_vpn.yml
  #  tags: vpn
