---
# pacman base package
- name: update and upgrade
  become: true
  pacman: update_cache=yes

- name: install base package
  become: true
  pacman: name={{ package }}

# - import_tasks: configure_pacman.yml
- import_tasks: install_yaourt.yml
- import_tasks: configure_locale.yml

- name: refresh key
  become: true
  command: pacman-key --refresh-keys

- import_tasks: nogui.yml
  when: not gui
  tags: nogui
- import_tasks: gui.yml
  when: gui
  tags: gui
- import_tasks: fonts.yml
  tags: fonts

- name: has wifi ?
  shell: dmesg | grep -i "wlan"
  register: has_wifi
  changed_when: has_wifi is success
  ignore_errors: true
  tags: wifi

- name: install wifi
  become: true
  pacman: name=wpa_supplicant state=present
  when: has_wifi is success
  tags: wifi

- name: get host misc packages
  command: yaourt -Q {{ item }}
  register: misc_presence
  with_items: "{{ misc_package }}"
  changed_when: misc_presence is failed
  when: misc_package is defined
  ignore_errors: yes
  tags: misc

- name: install host misc package
  become: false
  command: /usr/bin/yaourt --noconfirm --force -S {{ item.item }}
  with_items: "{{ misc_presence.results }}"
  when: item is failed
  ignore_errors: yes
  tags: misc

- name: enable host additional service
  become: true
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ additional_service }}"
  when: misc_presence.changed
  tags: misc

  #- import_tasks: install_vpn.yml
  #  tags: vpn
