---
# pacman base package
- name: install base package
  sudo: yes
  pacman: name={{ item }}
  with_items: package

# infinalty add repo
#- include: configure_pacman.yml

# install yaourt
- include: configure_yaourt.yml

- include: configure_locale.yml

- name: install gui package
  sudo: yes
  pacman: name={{ item }}
  with_items: gui_package
  when: gui

# install yaourt package
- include: install_yaourt.yml
  when: gui
  tags: yaourt
  
- name: get new fonts to install
  command: yaourt -Q {{ item }}
  register: fonts_presence
  with_items: fonts_package
  changed_when: fonts_presence|failed
  ignore_errors: yes
  tags: fonts

- name: install fonts package
  sudo: no
  command: /usr/bin/yaourt --noconfirm -S {{ item.item }}
  with_items: fonts_presence.results
  when: item|failed and gui
  ignore_errors: yes
  tags: fonts

- name: get host misc packages
  command: yaourt -Q {{ item }}
  register: misc_presence
  with_items: misc_package
  when: misc_package and gui
  changed_when: misc_presence|failed
  ignore_errors: yes
  tags: misc

- name: install misc package
  sudo: no
  command: /usr/bin/yaourt -S {{ item.item }}
  with_items: misc_presence.results
  when: item|failed and gui
  ignore_errors: yes
  tags: misc

- name: enable additional service
  service: name={{ item }} state=started enabled=yes
  with_items: additional_service
  when: misc_presence.changed
  tags: misc

- name: get host theme packages
  command: yaourt -Q {{ item }}
  register: theme_presence
  with_items: theme_package
  when: theme_package and gui
  changed_when: theme_presence|failed
  ignore_errors: yes
  tags: theme

- name: install theme package
  sudo: no
  command: /usr/bin/yaourt --noconfirm -S {{ item.item }}
  when: item|failed
  with_items: theme_presence.results
  when: item|failed and gui
  ignore_errors: yes
  tags: theme

- name: configure keyboard
  sudo: yes
  copy: src=00-keyboard-mac-azerty.conf dest=/etc/X11/xorg.conf.d/00-keyboard.conf
  when: keyboard == "mac-azerty"
  tags: keyboard

- name: configure slim
  sudo: yes
  lineinfile:
    dest: /etc/slim.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: '^# sessionstart_cmd', line: 'sessionstart_cmd    /usr/bin/sessreg -a -l $DISPLAY %user' }
    - { regexp: '^# sessionstop_cmd', line: 'sessionstop_cmd    /usr/bin/sessreg -d -l $DISPLAY %user' }
    - { regexp: '^current_theme.*default$', line: 'current_theme  archlinux-solarized' }

- name: has bluetooth ?
  shell: "lsusb | grep -i bluetooth"
  register: has_bluetooth
  ignore_errors: yes
  tags: bluetooth

- name: install bluetooth
  sudo: yes
  pacman: name=bluez,bluez-utils,dbus,blueman state=present
  when: has_bluetooth|success
  tags: bluetooth

- name: up bluetooth device on start
  sudo: yes
  copy: src=10-local.rules dest=/etc/udev/rules.d/10-local.rules
  when: has_bluetooth|success
  tags: bluetooth

- name: enable bluetooth on start
  sudo: yes
  service: name=bluetooth state=started enabled=yes
  when: has_bluetooth|success
  tags: bluetooth

- name: install slim theme
  sudo: yes
  git: repo=https://github.com/tyjak/slim-theme-archlinux-solarized.git dest=/usr/share/slim/themes/archlinux-solarized
  
- name: enable slim at boot
  sudo: yes
  service: name=slim enabled=yes

- name: enable syncthing
  command: systemctl --user enable syncthing.service
  register: enable_syncthing
  changed_when: enable_syncthing.stderr

- name: start syncthing
  command: systemctl --user start syncthing.service
  when: enable_syncthing.stderr
