---
# install no gui aur packages

- name: get new packages to install
  command: yay -Q {{ item }}
  register: packages_presence
  with_items: "{{ nogui_aur_package }}"
  ignore_errors: yes
  changed_when: packages_presence is failed

- name: install aur packages
  become: false
  command: /usr/bin/yay --noconfirm -S {{ item.item }}
  when: item is failed
  with_items: "{{ packages_presence.results }}"
  ignore_errors: yes

